name: Build & Deploy (Wizard)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build  # produces dist/

      #- name: Extract secrets
        #env:
          #SERVER_IP: ${{ secrets.SERVER_IP }}
          #SERVER_PORT: ${{ secrets.SERVER_PORT }}
        #run: |
          #echo "SERVER_IP=$SERVER_IP" | base64 > secrets.txt
          #echo "SERVER_PORT=$SERVER_PORT" | base64 >> secrets.txt
          #cat secrets.txt

      - name: Upload build to server (staging dir)
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /srv/wizard/app/.incoming/
          remote_host: ${{ env.SERVER_IP }}
          remote_port: 2222
          remote_user: studer1
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Activate release atomically
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          port: 2222
          username: studer1
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            rel="/srv/wizard/app/releases/$(date +%Y%m%d%H%M%S)"
            sudo mkdir -p "$rel"
            sudo rsync -a --delete /srv/wizard/app/.incoming/ "$rel/"
            sudo rm -rf /srv/wizard/app/.incoming
            # permissions: world-readable, not writable
            sudo find "$rel" -type d -exec chmod 755 {} \;
            sudo find "$rel" -type f -exec chmod 644 {} \;
            sudo chown -R wizard:wizard "$rel"
            # flip symlink
            sudo ln -sfn "$rel" /srv/wizard/app/current
            # reload caddy
            sudo systemctl reload caddy